apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: httpds.httpd.saberkan.fr
spec:
  group: httpd.saberkan.fr
  names:
    kind: Httpd
    listKind: HttpdList
    plural: httpds
    singular: httpd
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
